import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateProductionTables1789200000004 implements MigrationInterface {
    name = 'CreateProductionTables1789200000004'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "machine" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "machineType" character varying, "status" "public"."machine_status_enum" NOT NULL DEFAULT 'IDLE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" uuid, CONSTRAINT "PK_acc588900ffa841d96eb5fd566c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chemical_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "category" "public"."chemical_item_category_enum" NOT NULL DEFAULT 'CHEMICAL', "unit" character varying NOT NULL DEFAULT 'kg', "currentStock" numeric(14,3) NOT NULL DEFAULT '0', "minStockLevel" numeric(14,3) NOT NULL DEFAULT '0', "unitCost" numeric(12,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" uuid, CONSTRAINT "PK_3a929159fbed32ded41b111885c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recipe_ingredient" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dosageGPerKg" numeric(12,4) NOT NULL, "recipeId" uuid, "chemicalItemId" uuid, CONSTRAINT "PK_a13ac3f2cebdd703ac557c5377c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recipe" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "fabricType" character varying, "temperatureC" integer, "timeMinutes" integer, "liquorRatio" character varying, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" uuid, CONSTRAINT "PK_e365a2fedf57238d970e07825ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "batch" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batchNo" character varying NOT NULL, "recipe" character varying, "inputQty" numeric(12,3), "status" "public"."batch_status_enum" NOT NULL DEFAULT 'PENDING', "startTime" TIMESTAMP WITH TIME ZONE, "endTime" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "dyeingJobId" uuid, "machineId" uuid, "companyId" uuid, "recipeRefId" uuid, "parentBatchId" uuid, CONSTRAINT "PK_57da3b830b57bec1fd329dcaf43" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."stock_transaction_type_enum" NOT NULL, "quantity" numeric(14,3) NOT NULL, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "chemicalItemId" uuid, "batchId" uuid, "companyId" uuid, CONSTRAINT "PK_8a81a89b9130bda3a5277cce53a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lab_dip_sample" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sampleNo" integer NOT NULL, "recipeNotes" text, "photoUrl" character varying, "remarks" text, "status" "public"."lab_dip_sample_status_enum" NOT NULL DEFAULT 'CREATED', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "labDipId" uuid, "recipeRefId" uuid, CONSTRAINT "PK_a2440d4a71f671b6305d8886bd8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lab_dip" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "labDipNo" character varying NOT NULL, "customerName" character varying, "colour" character varying, "shadeCode" character varying, "status" "public"."lab_dip_status_enum" NOT NULL DEFAULT 'IN_PROGRESS', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "dyeingJobId" uuid, "productionRecipeId" uuid, "companyId" uuid, CONSTRAINT "PK_397a6b86a3a3dbe083991b4608e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "qc_inspection" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gsm" numeric(8,2), "width" character varying, "shrinkagePercent" numeric(6,2), "shadeResult" "public"."qc_inspection_shaderesult_enum", "colourFastnessResult" "public"."qc_inspection_colourfastnessresult_enum", "fabricDefects" integer NOT NULL DEFAULT '0', "overall" "public"."qc_inspection_overall_enum" NOT NULL, "remarks" text, "inspectedAt" TIMESTAMP NOT NULL DEFAULT now(), "batchId" uuid, "companyId" uuid, CONSTRAINT "PK_877ba0ad1f4114717411d8e2e99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerName" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "paymentDate" date NOT NULL, "mode" "public"."payment_mode_enum" NOT NULL DEFAULT 'BANK_TRANSFER', "referenceNo" character varying, "remarks" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" uuid, CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "batch_cost" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fabricCost" numeric(12,2) NOT NULL DEFAULT '0', "dyeChemicalCost" numeric(12,2) NOT NULL DEFAULT '0', "electricityCost" numeric(12,2) NOT NULL DEFAULT '0', "steamFuelCost" numeric(12,2) NOT NULL DEFAULT '0', "waterCost" numeric(12,2) NOT NULL DEFAULT '0', "labourCost" numeric(12,2) NOT NULL DEFAULT '0', "machineCost" numeric(12,2) NOT NULL DEFAULT '0', "otherCost" numeric(12,2) NOT NULL DEFAULT '0', "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "batchId" uuid, "companyId" uuid, CONSTRAINT "REL_c7dda90c9c6c5f5c573b1c6446" UNIQUE ("batchId"), CONSTRAINT "PK_24b8726a8e4c72e058f8c60ed0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "process_parameters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "factory_id" uuid, "process_id" uuid NOT NULL, "parameter_code" character varying(100) NOT NULL, "parameter_name" character varying(200) NOT NULL, "data_type" "public"."process_parameters_data_type_enum" NOT NULL, "unit" character varying(50), "is_required" boolean NOT NULL DEFAULT false, "display_order" integer NOT NULL DEFAULT '0', "default_value" text, "min_value" numeric(12,2), "max_value" numeric(12,2), "allowed_values" jsonb, "help_text" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bc6c29ffa72df95d1debd425332" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "processes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "factory_id" uuid, "category_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "process_code" character varying(50) NOT NULL, "description" text, "process_family" character varying(50) NOT NULL, "process_type" character varying(50) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_system_default" boolean NOT NULL DEFAULT false, "cloned_from_process_id" uuid, "has_executions" boolean NOT NULL DEFAULT false, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_566885de50f7d20a6df306c12e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "process_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "code" character varying(50) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "is_system_default" boolean NOT NULL DEFAULT false, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f47316921a3dd344a29b535e09e" UNIQUE ("name"), CONSTRAINT "UQ_c606a69a0a2ed9ffbc777e73658" UNIQUE ("code"), CONSTRAINT "PK_d4761fd669c8f07faf08abb207e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "process_route_step" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sequence" integer NOT NULL, "status" "public"."process_route_step_status_enum" NOT NULL DEFAULT 'PENDING', "isMandatory" boolean NOT NULL DEFAULT true, "requiresQcBefore" boolean NOT NULL DEFAULT true, "recipeId" character varying, "machineGroupId" character varying, "instructions" character varying, "expectedQuantity" numeric(12,3), "expectedCompletionDate" TIMESTAMP, "actualStartDate" TIMESTAMP, "actualCompletionDate" TIMESTAMP, "actualQuantity" numeric(12,3), "notes" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "routeId" uuid, "processId" uuid, CONSTRAINT "PK_e75fc6b5592672ac625b31ab85e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "process_route" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "routeName" character varying NOT NULL, "status" "public"."process_route_status_enum" NOT NULL DEFAULT 'ACTIVE', "templateName" character varying, "lockedAt" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "jobId" uuid, "companyId" uuid, CONSTRAINT "PK_c856b8fc415d23dc539c928ec53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "washing_batch_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying NOT NULL, "previousValue" jsonb, "newValue" jsonb, "changedBy" character varying NOT NULL, "changedByName" character varying, "reason" character varying, "approvedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "batchId" uuid, CONSTRAINT "PK_5297c36194550a89d2133285fdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "washing_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batchNo" character varying NOT NULL, "processType" "public"."washing_process_type_enum" NOT NULL, "machineId" character varying, "machineName" character varying, "operatorId" character varying, "operatorName" character varying, "recipeId" character varying, "recipeName" character varying, "status" "public"."washing_batch_status_enum" NOT NULL DEFAULT 'PENDING', "shift" character varying, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "inputQuantity" numeric(12,3) NOT NULL, "outputQuantity" numeric(12,3), "lossQuantity" numeric(12,3) DEFAULT '0', "lossPercentage" numeric(5,2) DEFAULT '0', "supervisorOverrideReason" character varying, "supervisorId" character varying, "remarks" text, "qualityNotes" text, "parameters" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "jobId" uuid, "routeStepId" uuid, "companyId" uuid, CONSTRAINT "UQ_872e6f7c7f6ed0d32af03bc09a2" UNIQUE ("batchNo"), CONSTRAINT "PK_50c1fcd98f87964f9c7cc721234" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dyeing_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batchNo" character varying NOT NULL, "processType" "public"."dyeing_batches_processtype_enum" NOT NULL, "recipeCode" character varying, "colour" character varying, "shadeCode" character varying, "labDipApprovalStatus" "public"."dyeing_batches_labdipapprovalstatus_enum" NOT NULL DEFAULT 'NOT_REQUIRED', "labDipReference" character varying, "customerApproved" boolean, "customerApprovedAt" TIMESTAMP, "inputQuantity" numeric(12,3) NOT NULL, "outputQuantity" numeric(12,3), "lossQuantity" numeric(12,3), "lossPercentage" numeric(5,2), "status" "public"."dyeing_batches_status_enum" NOT NULL DEFAULT 'PENDING', "machineId" character varying, "machineName" character varying, "operatorId" character varying, "operatorName" character varying, "shift" character varying, "targetParameters" jsonb, "actualParameters" jsonb, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "remarks" text, "supervisorOverrideReason" character varying, "supervisorId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "job_id" uuid, "route_step_id" uuid, "recipe_id" uuid, "company_id" uuid, CONSTRAINT "UQ_bcd27282d641ab19d1a19256bb0" UNIQUE ("batchNo"), CONSTRAINT "PK_052cb695cd9654794a5be9cdb0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dyeing_batch_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying NOT NULL, "previousValue" jsonb, "newValue" jsonb, "changedBy" character varying, "reason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "batch_id" uuid, CONSTRAINT "PK_03d9b0f033de2d5c6a88f306f45" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dyeing_process_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sequenceNumber" integer NOT NULL, "eventName" character varying NOT NULL, "description" character varying, "actualParameters" jsonb, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "remarks" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "batch_id" uuid, CONSTRAINT "PK_1c3f176d1a515c3f7b7e59444cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "finishing_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "jobId" uuid NOT NULL, "processId" uuid NOT NULL, "routeStepId" uuid, "batchNumber" character varying NOT NULL, "processType" "public"."finishing_process_type_enum" NOT NULL DEFAULT 'SOFT_FINISH', "status" "public"."finishing_batch_status_enum" NOT NULL DEFAULT 'PENDING', "machineId" character varying, "machineCode" character varying, "recipeId" character varying, "recipeName" character varying, "recipeVersion" character varying, "operatorId" character varying, "operatorName" character varying, "shift" character varying, "inputQuantity" numeric(12,3) NOT NULL, "outputQuantity" numeric(12,3), "lossQuantity" numeric(12,3), "lossPercentage" numeric(5,2), "uom" character varying, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "pausedAt" TIMESTAMP, "durationMinutes" numeric(10,2), "actualParameters" jsonb, "targetParameters" jsonb, "remarks" character varying, "qualityNotes" character varying, "finalWidth" integer, "finalShrinkage" numeric(5,2), "supervisorOverride" boolean NOT NULL DEFAULT false, "supervisorId" character varying, "supervisorOverrideReason" character varying, "supervisorOverrideAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, CONSTRAINT "PK_d1383c85edacc44bc37169f0a96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "finishing_batch_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "batchId" uuid NOT NULL, "action" character varying NOT NULL, "previousValues" character varying, "newValues" character varying, "reason" character varying, "userId" character varying, "userName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f3decb405a16db1a8c9379eb9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drying_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "jobId" uuid NOT NULL, "processId" uuid NOT NULL, "routeStepId" uuid, "batchNumber" character varying NOT NULL, "processType" "public"."drying_batches_processtype_enum" NOT NULL DEFAULT 'AIR_DRY', "status" "public"."drying_batches_status_enum" NOT NULL DEFAULT 'PENDING', "machineId" character varying, "machineCode" character varying, "recipeId" character varying, "recipeName" character varying, "recipeVersion" character varying, "operatorId" character varying, "operatorName" character varying, "shift" character varying, "inputQuantity" numeric(12,3) NOT NULL, "outputQuantity" numeric(12,3), "lossQuantity" numeric(12,3), "lossPercentage" numeric(5,2), "uom" character varying, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "pausedAt" TIMESTAMP, "durationMinutes" numeric(10,2), "actualParameters" jsonb, "targetParameters" jsonb, "remarks" character varying, "qualityNotes" character varying, "supervisorOverride" boolean NOT NULL DEFAULT false, "supervisorId" character varying, "supervisorOverrideReason" character varying, "supervisorOverrideAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, CONSTRAINT "PK_830475f406f5c4b74ff7b49bf3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drying_batch_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "batchId" uuid NOT NULL, "action" character varying NOT NULL, "previousValues" character varying, "newValues" character varying, "reason" character varying, "userId" character varying, "userName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_25a0f5017e232a740008d6a4c02" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "drying_batch_audit"`);
        await queryRunner.query(`DROP TABLE "drying_batches"`);
        await queryRunner.query(`DROP TABLE "finishing_batch_audit"`);
        await queryRunner.query(`DROP TABLE "finishing_batches"`);
        await queryRunner.query(`DROP TABLE "washing_batch_audit"`);
        await queryRunner.query(`DROP TABLE "washing_batches"`);
        await queryRunner.query(`DROP TABLE "dyeing_batch_audit"`);
        await queryRunner.query(`DROP TABLE "dyeing_batches"`);
        await queryRunner.query(`DROP TABLE "dyeing_process_events"`);
        await queryRunner.query(`DROP TABLE "process_route_step"`);
        await queryRunner.query(`DROP TABLE "process_route"`);
        await queryRunner.query(`DROP TABLE "process_categories"`);
        await queryRunner.query(`DROP TABLE "processes"`);
        await queryRunner.query(`DROP TABLE "process_parameters"`);
        await queryRunner.query(`DROP TABLE "batch_cost"`);
        await queryRunner.query(`DROP TABLE "batch"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TABLE "qc_inspection"`);
        await queryRunner.query(`DROP TABLE "lab_dip_sample"`);
        await queryRunner.query(`DROP TABLE "lab_dip"`);
        await queryRunner.query(`DROP TABLE "stock_transaction"`);
        await queryRunner.query(`DROP TABLE "recipe_ingredient"`);
        await queryRunner.query(`DROP TABLE "recipe"`);
        await queryRunner.query(`DROP TABLE "chemical_item"`);
        await queryRunner.query(`DROP TABLE "machine"`);
    }
}
